<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Student;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $students = [
            [
                'name' => 'Ahmad Rizki',
                'age' => 16,
                'gender' => 'male',
                'contact' => [
                    'phone' => '081234567890',
                    'email' => 'ahmad.rizki@student.com',
                    'address' => 'Jl. Merdeka No. 123, Jakarta Pusat',
                    'emergency_contact' => '081234567891',
                    'parent_name' => 'Bapak Rizki',
                ],
                'academic' => [
                    'grade' => '10',
                    'class' => 'X RPL 1',
                    'student_id' => 'SMK2025001',
                    'major' => 'Rekayasa Perangkat Lunak',
                    'entry_year' => 2025,
                    'period' => 'Semester Ganjil',
                ],
                'data' => [
                    'nisn' => '0051234567',
                    'nik' => '3175012345670001',
                    'birth_place' => 'Jakarta',
                    'birth_date' => '2009-05-15',
                    'religion' => 'Islam',
                    'blood_type' => 'A',
                    'height' => 165,
                    'weight' => 55,
                    'hobbies' => ['Coding', 'Gaming', 'Reading'],
                    'achievements' => ['Juara 1 Coding Competition 2024'],
                ],
            ],
            [
                'name' => 'Siti Nurhaliza',
                'age' => 15,
                'gender' => 'female',
                'contact' => [
                    'phone' => '082345678901',
                    'email' => 'siti.nurhaliza@student.com',
                    'address' => 'Jl. Sudirman No. 45, Jakarta Selatan',
                    'emergency_contact' => '082345678902',
                    'parent_name' => 'Ibu Haliza',
                ],
                'academic' => [
                    'grade' => '10',
                    'class' => 'X TKJ 1',
                    'student_id' => 'SMK2025002',
                    'major' => 'Teknik Komputer dan Jaringan',
                    'entry_year' => 2025,
                    'period' => 'Semester Ganjil',
                ],
                'data' => [
                    'nisn' => '0051234568',
                    'nik' => '3175012345670002',
                    'birth_place' => 'Bandung',
                    'birth_date' => '2009-08-20',
                    'religion' => 'Islam',
                    'blood_type' => 'B',
                    'height' => 158,
                    'weight' => 48,
                    'hobbies' => ['Design', 'Photography', 'Music'],
                    'achievements' => ['Juara 2 Design Competition 2024'],
                ],
            ],
            [
                'name' => 'Budi Santoso',
                'age' => 17,
                'gender' => 'male',
                'contact' => [
                    'phone' => '083456789012',
                    'email' => 'budi.santoso@student.com',
                    'address' => 'Jl. Gatot Subroto No. 78, Jakarta Barat',
                    'emergency_contact' => '083456789013',
                    'parent_name' => 'Bapak Santoso',
                ],
                'academic' => [
                    'grade' => '11',
                    'class' => 'XI RPL 2',
                    'student_id' => 'SMK2024003',
                    'major' => 'Rekayasa Perangkat Lunak',
                    'entry_year' => 2024,
                    'period' => 'Semester Ganjil',
                ],
                'data' => [
                    'nisn' => '0041234567',
                    'nik' => '3175012345670003',
                    'birth_place' => 'Surabaya',
                    'birth_date' => '2008-03-10',
                    'religion' => 'Kristen',
                    'blood_type' => 'O',
                    'height' => 170,
                    'weight' => 60,
                    'hobbies' => ['Football', 'Programming', 'Robotics'],
                    'achievements' => ['Juara 1 Robotics Competition 2023', 'Best Student 2024'],
                ],
            ],
            [
                'name' => 'Dewi Kartika',
                'age' => 16,
                'gender' => 'female',
                'contact' => [
                    'phone' => '084567890123',
                    'email' => 'dewi.kartika@student.com',
                    'address' => 'Jl. Diponegoro No. 99, Jakarta Timur',
                    'emergency_contact' => '084567890124',
                    'parent_name' => 'Ibu Kartika',
                ],
                'academic' => [
                    'grade' => '10',
                    'class' => 'X MM 1',
                    'student_id' => 'SMK2025004',
                    'major' => 'Multimedia',
                    'entry_year' => 2025,
                    'period' => 'Semester Ganjil',
                ],
                'data' => [
                    'nisn' => '0051234569',
                    'nik' => '3175012345670004',
                    'birth_place' => 'Yogyakarta',
                    'birth_date' => '2009-11-25',
                    'religion' => 'Islam',
                    'blood_type' => 'AB',
                    'height' => 160,
                    'weight' => 50,
                    'hobbies' => ['Drawing', 'Animation', 'Video Editing'],
                    'achievements' => ['Juara 3 Animation Festival 2024'],
                ],
            ],
            [
                'name' => 'Eko Prasetyo',
                'age' => 15,
                'gender' => 'male',
                'contact' => [
                    'phone' => '085678901234',
                    'email' => 'eko.prasetyo@student.com',
                    'address' => 'Jl. Ahmad Yani No. 56, Jakarta Utara',
                    'emergency_contact' => '085678901235',
                    'parent_name' => 'Bapak Prasetyo',
                ],
                'academic' => [
                    'grade' => '10',
                    'class' => 'X TKJ 2',
                    'student_id' => 'SMK2025005',
                    'major' => 'Teknik Komputer dan Jaringan',
                    'entry_year' => 2025,
                    'period' => 'Semester Genap',
                ],
                'data' => [
                    'nisn' => '0051234570',
                    'nik' => '3175012345670005',
                    'birth_place' => 'Semarang',
                    'birth_date' => '2009-06-30',
                    'religion' => 'Islam',
                    'blood_type' => 'A',
                    'height' => 168,
                    'weight' => 58,
                    'hobbies' => ['Networking', 'Gaming', 'Basketball'],
                    'achievements' => ['Participant Network Security Workshop 2024'],
                ],
            ],
            [
                'name' => 'Fitri Handayani',
                'age' => 16,
                'gender' => 'female',
                'contact' => [
                    'phone' => '086789012345',
                    'email' => 'fitri.handayani@student.com',
                    'address' => 'Jl. Veteran No. 34, Tangerang',
                    'emergency_contact' => '086789012346',
                    'parent_name' => 'Ibu Handayani',
                ],
                'academic' => [
                    'grade' => '11',
                    'class' => 'XI MM 1',
                    'student_id' => 'SMK2024006',
                    'major' => 'Multimedia',
                    'entry_year' => 2024,
                    'period' => 'Semester Genap',
                ],
                'data' => [
                    'nisn' => '0041234568',
                    'nik' => '3175012345670006',
                    'birth_place' => 'Tangerang',
                    'birth_date' => '2008-09-12',
                    'religion' => 'Islam',
                    'blood_type' => 'B',
                    'height' => 162,
                    'weight' => 52,
                    'hobbies' => ['Photography', 'Graphic Design', 'Reading'],
                    'achievements' => ['Juara 1 Photography Contest 2023', 'Best Portfolio 2024'],
                ],
            ],
            [
                'name' => 'Galih Pratama',
                'age' => 17,
                'gender' => 'male',
                'contact' => [
                    'phone' => '087890123456',
                    'email' => 'galih.pratama@student.com',
                    'address' => 'Jl. Cendrawasih No. 12, Bekasi',
                    'emergency_contact' => '087890123457',
                    'parent_name' => 'Bapak Pratama',
                ],
                'academic' => [
                    'grade' => '12',
                    'class' => 'XII RPL 1',
                    'student_id' => 'SMK2023007',
                    'major' => 'Rekayasa Perangkat Lunak',
                    'entry_year' => 2023,
                    'period' => 'Semester Genap',
                ],
                'data' => [
                    'nisn' => '0031234567',
                    'nik' => '3175012345670007',
                    'birth_place' => 'Bekasi',
                    'birth_date' => '2007-12-05',
                    'religion' => 'Islam',
                    'blood_type' => 'O',
                    'height' => 175,
                    'weight' => 65,
                    'hobbies' => ['Web Development', 'Mobile Apps', 'Cyber Security'],
                    'achievements' => ['Juara 1 Hackathon 2022', 'Juara 2 Web Competition 2023', 'Best Graduating Student Candidate 2025'],
                ],
            ],
            [
                'name' => 'Hana Permata',
                'age' => 15,
                'gender' => 'female',
                'contact' => [
                    'phone' => '088901234567',
                    'email' => 'hana.permata@student.com',
                    'address' => 'Jl. Melati No. 88, Depok',
                    'emergency_contact' => '088901234568',
                    'parent_name' => 'Ibu Permata',
                ],
                'academic' => [
                    'grade' => '10',
                    'class' => 'X RPL 1',
                    'student_id' => 'SMK2025008',
                    'major' => 'Rekayasa Perangkat Lunak',
                    'entry_year' => 2025,
                    'period' => 'Semester Ganjil',
                ],
                'data' => [
                    'nisn' => '0051234571',
                    'nik' => '3175012345670008',
                    'birth_place' => 'Depok',
                    'birth_date' => '2009-04-18',
                    'religion' => 'Islam',
                    'blood_type' => 'A',
                    'height' => 155,
                    'weight' => 45,
                    'hobbies' => ['UI/UX Design', 'Writing', 'Art'],
                    'achievements' => ['Best New Student 2025'],
                ],
            ],
            [
                'name' => 'Indra Gunawan',
                'age' => 16,
                'gender' => 'male',
                'contact' => [
                    'phone' => '089012345678',
                    'email' => 'indra.gunawan@student.com',
                    'address' => 'Jl. Mawar No. 21, Bogor',
                    'emergency_contact' => '089012345679',
                    'parent_name' => 'Bapak Gunawan',
                ],
                'academic' => [
                    'grade' => '11',
                    'class' => 'XI TKJ 1',
                    'student_id' => 'SMK2024009',
                    'major' => 'Teknik Komputer dan Jaringan',
                    'entry_year' => 2024,
                    'period' => 'Semester Genap',
                ],
                'data' => [
                    'nisn' => '0041234569',
                    'nik' => '3175012345670009',
                    'birth_place' => 'Bogor',
                    'birth_date' => '2008-07-22',
                    'religion' => 'Islam',
                    'blood_type' => 'B',
                    'height' => 172,
                    'weight' => 62,
                    'hobbies' => ['Network Administration', 'Server Management', 'Chess'],
                    'achievements' => ['Cisco Certified Network Associate 2024'],
                ],
            ],
            [
                'name' => 'Julia Safitri',
                'age' => 17,
                'gender' => 'female',
                'contact' => [
                    'phone' => '081123456789',
                    'email' => 'julia.safitri@student.com',
                    'address' => 'Jl. Anggrek No. 67, Jakarta Selatan',
                    'emergency_contact' => '081123456790',
                    'parent_name' => 'Ibu Safitri',
                ],
                'academic' => [
                    'grade' => '12',
                    'class' => 'XII MM 1',
                    'student_id' => 'SMK2023010',
                    'major' => 'Multimedia',
                    'entry_year' => 2023,
                    'period' => 'Semester Genap',
                ],
                'data' => [
                    'nisn' => '0031234568',
                    'nik' => '3175012345670010',
                    'birth_place' => 'Jakarta',
                    'birth_date' => '2007-10-08',
                    'religion' => 'Kristen',
                    'blood_type' => 'AB',
                    'height' => 163,
                    'weight' => 53,
                    'hobbies' => ['Video Production', '3D Modeling', 'Music Composition'],
                    'achievements' => ['Juara 1 Film Pendek Competition 2022', 'Best Multimedia Portfolio 2023', 'National Finalist Short Film 2024'],
                ],
            ],
        ];

        foreach ($students as $studentData) {
            Student::create([
                'name' => $studentData['name'],
                'data' => [
                    'age' => $studentData['age'],
                    'gender' => $studentData['gender'],
                    'contact' => $studentData['contact'],
                    'academic' => $studentData['academic'],
                    'biodata' => $studentData['data'],
                ],
            ]);
        }
    }
}
